core/urls.py
from django.conf.urls import url, include
from . import views


app_name = 'core'

urlpatterns = [
    url(r'^addmult/$', views.addmult, name='addmult'),

]

elearning/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'elearning'

urlpatterns = [

    url(r'^$', auth_views.LoginView.as_view(template_name='admin/login.html'), name="login"),
    url(r'^home/$', views.index, name='index'),
    url(r'^admin_index/$', views.admin_index, name='admin_index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='admin/login.html'), name="login"),
    url(r'^accounts/password_reset/$', auth_views.PasswordResetView.as_view(), name="password_reset"),
    url(r'^accounts/password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    url(r'^accounts/reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),

    url(r'^valutazione/', include(('valutazione.urls', 'valutazione'), namespace='valutazione')),
    url(r'^Add/', include(('core.urls', 'core'), namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

valutazione/urls.py
from django.conf.urls import url, include
from . import views


app_name = 'valutazione'

urlpatterns = [
    url(r'^valutazione/$', views.cert, name='cert'),
    url(r'^level/$', views.level, name='level'),
    url(r'^upload/$', views.upload, name='upload'),

]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class Rank(models.Model):
    desc = models.CharField(max_length=500)

    def __str__(self):
        return self.desc

    class Meta:
        verbose_name = "Rank"
        verbose_name_plural = "Ranks"


class Position(models.Model):
    desc = models.CharField(max_length=500)

    def __str__(self):
        return self.desc

    class Meta:
        verbose_name = "Position"
        verbose_name_plural = "Positions"


class Formazione(models.Model):
    desc = models.CharField(max_length=500)

    def __str__(self):
        return self.desc

    class Meta:
        verbose_name = "Formazione"
        verbose_name_plural = "Formaziones"


class Utente(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', unique=True)
    area = models.CharField(max_length=500, null=True)
    rank = models.ForeignKey(Rank, on_delete=models.DO_NOTHING, null=True)
    position = models.ForeignKey(Position, on_delete=models.DO_NOTHING, null=True)
    formazione = models.ForeignKey(Formazione, on_delete=models.DO_NOTHING, null=True)
    resposabile = models.ForeignKey(User, on_delete=models.CASCADE, related_name='responsabile')

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Dipendente"
        verbose_name_plural = "Dipendenti"

core/views.py
from django.shortcuts import render
from core.models import Utente
from corso.models import *
from valutazione.models import Skill


def addmult(request):
    lista_vendor = []
    lista_tech = None
    lista_user_select = ''
    lista_ambito_select = []
    if request.method == 'POST':
        post = request.POST
        print(post)
        lista_user_select = post['user']
        a = Anello1.objects.get(pk=post['ambito'])
        lista_ambito_select = [a.id, a.desc]
        if 'ambito' in post:
            s = Skill.objects.filter(ambito__id=post['ambito'])
            for x in s:
                lista_vendor.append(x.vendor.desc)
            print(lista_vendor)
            lista_vendor = list(set(lista_vendor))

    print(lista_vendor)
    data_to_template = {
        'nav' 		: '',
        'subnav' 		: '',
        'title_b' 	: 'Aggiunge Utente Skill',
        'title_sma' 	: "",
        'html_headr'	: '<li><a href="#">Il mio profilo</a></li>',
        'lista_user': Utente.objects.all().order_by('user__username'),
        'lista_ambito': Anello1.objects.all().order_by('desc'),
        'lista_vendor': lista_vendor,
        'lista_tech': lista_tech,
        'lista_user_select': lista_user_select,
        'lista_ambito_select': lista_ambito_select,
    }

    return render(request, 'core/addmult.html',  data_to_template)

core/templates/core/addmult.html
{% extends 'core/index.html' %}

{% block head_title %}Index{% endblock %}

{% block body_main %}
    <div class="card">
        <div class="card-body">

            <div class="form-row">
                <form action="{% url 'core:addmult'%}"  method="POST" enctype="multipart/form-data" class="form-horizontal" id="addmult1" novalidate="novalidate">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="col-form-label">Selezionare il Dipendente</label>
                        <select class="custom-select" name="user">
                            <option>{{ lista_user_select }}</option>
                            {% for user in lista_user %}
                                <option value="{{ user.user }}">{{ user.user }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group ">
                        <label class="col-form-label">Selezionare il Ambito</label>
                        <select class="custom-select" name="ambito">
                            <option value="{{ lista_ambito_select.0 }}">{{ lista_ambito_select.1 }}</option>
                            {% for user in lista_ambito %}
                                <option value="{{ user.pk }}">{{ user.desc }}</option>
                            {% endfor %}
                        </select>
                    </div>



                    <div class="form-group" >
                        <label class="col-form-label">Selezionare il Vendor</label>
                        <select class="custom-select" name="vendor">
                            <option></option>
                            {% for user in lista_vendor %}
                                <option value="{{ user }}">{{ user }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Selezionare il Technologia</label>
                        <select class="custom-select" name="tech">
                            <option></option>
                            {% for user in lista_tech %}
                                <option value="{{ user.pk }}">{{ user.desc }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <input class="btn btn-primary btn-sm" form="addmult1" type="submit" value="search"/>
                </form>
            </div>

        </div>
    </div>
{% endblock %}

core/templates/core/admin.html
{% extends 'core/index.html' %}

{% block head_title %}Index{% endblock %}

{% block body_main %}

{% endblock %}

core/templates/core/body-index.html
{% extends 'core/index.html' %}
{%  load staticfiles %}

{% block custom_page_level_css %}
  <script src="https://cdn.anychart.com/releases/v8/js/anychart-base.min.js?hcode=be5162d915534272a57d0bb781d27f2b"></script>
  <script src="https://cdn.anychart.com/releases/v8/js/anychart-sunburst.min.js?hcode=be5162d915534272a57d0bb781d27f2b"></script>
  <script src="https://cdn.anychart.com/releases/v8/js/anychart-ui.min.js?hcode=be5162d915534272a57d0bb781d27f2b"></script>
  <script src="https://cdn.anychart.com/releases/v8/js/anychart-exports.min.js?hcode=be5162d915534272a57d0bb781d27f2b"></script>
  <script src="https://cdn.anychart.com/releases/v8/js/anychart-data-adapter.min.js?hcode=be5162d915534272a57d0bb781d27f2b"></script>
  <script src="https://cdn.anychart.com/releases/v8/themes/sea.min.js"></script>
  <link href="https://cdn.anychart.com/releases/v8/css/anychart-ui.min.css?hcode=be5162d915534272a57d0bb781d27f2b" type="text/css" rel="stylesheet">
  <link href="https://cdn.anychart.com/releases/v8/fonts/css/anychart-font.min.css?hcode=be5162d915534272a57d0bb781d27f2b" type="text/css" rel="stylesheet">
  <style type="text/css">
		html,
		body,
		#container {
			width: 100%;
			height: 2000px;
			margin: 0;
			padding: 0;
		}
  		#container2 {
			width: 100%;
			height: 100%;
			margin: 0;
			padding: 5px;
            border-radius: 5px;
            background-color: rgba(147, 151, 156, 0.38);
		}
  </style>
{% endblock %}

{% block custom_page_level_javascript %}

    <script>
		anychart.onDocumentReady(function () {
			// The data used in this sample can be obtained from the CDN
			// https://cdn.anychart.com/samples/sunburst-charts/employee-count-by-country/data.json
                    data = {{ dict|safe }};



					// makes tree from the data for the sample
					var dataTree = anychart.data.tree(data);

					// create sunburst chart
					var chart = anychart.sunburst(dataTree);

					// set calculation mode
					chart.calculationMode('parent-independent');

					// descending sort data
					chart.sort('desc');

					// set chart title
					// chart.title('Radar Space source AnyChart Core');

					// set custom palette
					chart.palette([
						'#f9fffd',
                        '#ff9a32',
                        'rgba(82,64,145,0.56)',
                        '#ff8470',
                        '#80c3ff',
						'#355a85',
                        '#66a64a',
                        '#fab353',
                        '#aaa2d8',
                        '#6097ce',
						'#343434',
                        '#eab8a8',
                        '#895070',
                        '#89b5ab',
                        '#8e4dbd'
					]);

					// format chart labels
					chart.labels().format("{%Name}");

                    // enable HTML for labels
                    chart.tooltip().useHtml(true);

					// format tooltip
					chart.tooltip().format("<h3>{%name}</h2><br><br>{%lista_work_amb}{%lista_work_ven}{%list_worker_tech}{%lista_worker_cap}");



					// set container id for the chart
					chart.container('container');

					// initiate chart drawing
					chart.draw();

					function format(bytes) {
						var kb = bytes / 1024;
						var mb = bytes / 1024 / 1024;

						var units = {
							KB: kb,
							MB: mb
						};

						var lastUnit = 'B';
						var lastValue = bytes;

						for (var u in units) {
							if (units[u] < 1) {
								return lastValue
							}
							lastUnit = u;
							lastValue = units[u].toFixed(2);
						}

						return lastValue
					}
				});

</script>
{% endblock %}

{% block body_main %}
    <div class="card">


            <div class="col-lg-12"><div id="container"></div></div>



    </div>
{% endblock %}

core/templates/core/empty.html
{% extends 'core/index.html' %}

{% block head_title %}Index{% endblock %}

{% block body_main %}



{% endblock %}

core/templates/core/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-4">{{ field.label_tag }}</label>
        <div class="form-control">{{ field }}</div>
    </div>
{% endfor %}

core/templates/core/index.html
<!doctype html>
<html class="no-js" lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>DGS Spa {% block head_title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'admin-center/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin-center/assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin-center/assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'admin-center/assets/css/metisMenu.css' %}">
    <link rel="stylesheet" href="{% static 'admin-center/assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin-center/assets/css/slicknav.min.css' %}">
    <!-- amchart css -->
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />

    <!-- others css -->
    <link rel="stylesheet" href="{% static 'admin-center/assets/css/typography.css' %}">
    <link rel="stylesheet" href="{% static 'admin-center/assets/css/default-css.css' %}">
    <link rel="stylesheet" href="{% static 'admin-center/assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'admin-center/assets/css/responsive.css' %}">
    <!-- modernizr css -->
    <script src="{% static 'admin-center/assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'admin-center/favicon.ico' %}" />
    {% block custom_page_level_css %}{% endblock %}
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- preloader area end -->
    <!-- page container area start -->
    <div class="page-container">
        <!-- sidebar menu area start -->
        {% include 'core/menu.html' %}
        <!-- sidebar menu area end -->
        <!-- main content area start -->
        <div class="main-content" style="background-color: rgba(48,54,65,0.91)">
            <!-- header area start -->

                <div class="header-area" style="background-color: rgba(48,54,65,0.91)">
                    <div class="row align-items-center">
                        <!-- nav and search button -->
                        <div class="col-md-6 col-sm-8 clearfix">
                            <div class="nav-btn">
                                <ul class="notification-area">
                                    <li><i class="ti-menu"></i></li>
                                </ul>
                            </div>
                        </div>
                        <!-- profile info & task notification -->
                        <div class="col-md-6 col-sm-4 ">
                            <ul class="notification-area pull-right">
                                <li class="dropdown">
                                    <i class="ti-user dropdown-toggle" data-toggle="dropdown"><a style="float: left; margin-bottom: 0; padding-top: 6px">{{ user.username }}&nbsp;&nbsp;</a></i>
                                    <div class="dropdown-menu bell-notify-box notify-box" style="width: 200px">
                                            <div class="list-group" >
                                                <a href="#" class="list-group-item list-group-item-action active">User : {{ user.username }}</a>
                                                <a href="#" class="list-group-item list-group-item-action"><i class="fa fa-user"></i> My Profile</a>
                                                <a href="/usr-manage/" class="list-group-item list-group-item-action"><i class="fa fa-search"></i> Sessioni</a>
                                                <a href="/admin/logout/" class="list-group-item list-group-item-action" style="background-color: rgba(143, 153, 144, 0.88)"><i class="fa fa-key"></i> Log Out</a>
                                            </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="main-content-inner" style="padding: 0">
                        {% block body_main %}{% endblock %}
                </div>
        </div>
        <!-- footer area start-->
        <footer>
            <div class="footer-area" style="background-color: rgba(48,54,65,0.91)">
                <p>© Copyright 2018. All right reserved  <a href="#">DGS Spa</a>.</p>
            </div>
        </footer>

    </div>

    <script src="{% static 'admin-center/assets/js/vendor/jquery-2.2.4.min.js' %}"></script>
    <!-- bootstrap 4 js -->
    <script src="{% static 'admin-center/assets/js/popper.min.js' %}"></script>
    <script src="{% static 'admin-center/assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'admin-center/assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'admin-center/assets/js/metisMenu.min.js' %}"></script>
    <script src="{% static 'admin-center/assets/js/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'admin-center/assets/js/jquery.slicknav.min.js' %}"></script>
    <!-- others plugins -->
    <script src="{% static 'admin-center/assets/js/plugins.js' %}"></script>
    <script src="{% static 'admin-center/assets/js/scripts.js' %}"></script>

    {% block custom_page_level_javascript %}{% endblock %}
    <script>
            jQuery(document).ready(function() {
               App.init(); // initlayout and core plugins
               Index.init();

               Index.initCharts(); // init index page's custom scripts
               Index.initChat();
               Index.initMiniCharts();
               Index.initDashboardDaterange();
               Index.initIntro();
               Tasks.initDashboardWidget();

               {% block custom_init_javascript %}{% endblock %}

            });

            function hide_message(){
                alert("Il messaggio verra' nascosto");
                $.cookie("session_show", 1);
            }

            if (!$.cookie('session_show')) {

                var total_session = {% if double_session %}{{double_session}}{% else %}0{% endif %};

                if ( total_session > 1 ){
                    setTimeout(function () {
                        var unique_id = $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: 'SESSION ALERT',
                            // (string | mandatory) the text inside the notification
                            text: 'Sono presenti sessioni multiple. [ ' + total_session + ' ] <br><a href="/usr-manage/" target="_blank">controlla</a> - <a href="#" onclick="hide_message();" >nascondi</a>',
                            // (string | optional) the image to display on the left
                            image: '/static/custom/img/alert-icon.png',
                            // (bool | optional) if you want it to fade out on its own or just sit there
                            sticky: true,
                            // (int | optional) the time you want it to be alive for before fading out
                            time: '',
                            // (string | optional) the class name you want to apply to that specific message
                            class_name: 'my-sticky-class'
                        });

                        // You can have it return a unique id, this can be used to manually remove it later using
                        setTimeout(function () {
                            $.gritter.remove(unique_id, {
                                fade: true,
                                speed: 'slow'
                            });
                        }, 25000);
                    }, 1000);


                }
            }


        </script>
</body>

</html>

core/templates/core/menu.html
{% load staticfiles %}

        <div class="sidebar-menu">
            <div class="sidebar-header">
                <div class="logo" style="margin: 0;padding:0">
                    <a href="{% url 'admin_index'  %}"><img  src="{% static 'admin-center/logo-dgs-group-white.png' %}" alt="logo"></a>
                </div>
            </div>
            <div class="main-menu">

                <div class="menu-inner">
                    <nav>
                        <ul class="metismenu" id="menu">
                            <li>
                                <div class="search-box" style="width: 100%">
                                    <form action="" method="GET">
                                        <input type="text" name="search" placeholder="Search..." required style="width: 100%; height: 40px">
                                        <i class="ti-search"></i>
                                    </form>
                                </div>
                            </li>
                            {% for group in user.groups.all %}
                                {% if group.name == 'diretore' %}
                                    <li {% ifequal nav "home" %}class="active"{% endifequal %}>
                                        <a href="{% url 'admin_index'  %}" aria-expanded="true" ><i style="color: #8d97ad" class="ti-pie-chart"></i><span>Dashboard</span></a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% for group in user.groups.all %}
                                {% if group.name == 'diretore' %}
                                    <li {% ifequal nav "gen" %}class="active"{% endifequal %}>
                                        <a href="javascript:void(0)" aria-expanded="true"><i style="color: #8d97ad" class="ti-pie-chart"></i><span>Gestione</span></a>
                                        <ul class="collapse">
                                            <li {% ifequal subnav "gen-ser" %}class="active"{% endifequal %}>
                                                <a href="/admin/corso/corso/add/" target="_blank">
                                                    <i style="color: #8d97ad" class="ti-plus"></i>&nbsp;&nbsp;&nbsp;Corsi
                                                </a>
                                            </li>
                                            <li {% ifequal subnav "gen-sys" %}class="active"{% endifequal %}>
                                                <a href="/admin/corso/certificazione/add/" target="_blank">
                                                    <i style="color: #8d97ad" class="ti-plus"></i>&nbsp;&nbsp;&nbsp;Certificati
                                                </a>
                                            </li>
                                            <li {% ifequal subnav "gen-user" %}class="active"{% endifequal %}>
                                                <a href="/admin/auth/user/add/" target="_blank">
                                                    <i style="color: #8d97ad" class="ti-plus"></i>&nbsp;&nbsp;&nbsp;Utente
                                                </a>
                                            </li>
                                            <li {% ifequal subnav "gen-user" %}class="active"{% endifequal %}>
                                                <a href="/admin/core/utente/add/" target="_blank">
                                                    <i style="color: #8d97ad" class="ti-plus"></i>&nbsp;&nbsp;&nbsp;Dipendente
                                                </a>
                                            </li>
                                            <li {% ifequal subnav "gen-user" %}class="active"{% endifequal %}>
                                                <a href="javascript:void(0)" aria-expanded="true"><i style="color: #8d97ad" class="ti-pie-chart"></i><span>Skills</span></a>
                                                <ul class="collapse">
                                                    <li>
                                                        <a href="/admin/valutazione/user_skill/add/" target="_blank">
                                                            <i style="color: #8d97ad" class="ti-plus"></i>&nbsp;&nbsp;&nbsp;Skill Unica
                                                        </a>
                                                    </li>
                                                    <li {% ifequal subnav "gen-user" %}class="active"{% endifequal %}>
                                                        <a href="{% url 'core:addmult' %}" target="_blank">
                                                            <i style="color: #8d97ad" class="ti-plus"></i>&nbsp;&nbsp;&nbsp;Skill Multiplo
                                                        </a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li {% ifequal subnav "gen-user" %}class="active"{% endifequal %}>
                                                <a href="/admin/core/utente/" target="_blank">
                                                    <i style="color: #8d97ad" class="ti-close"></i>&nbsp;&nbsp;&nbsp;Del Utente
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% for group in user.groups.all %}
                                {% if group.name == 'diretore' %}
                                    <li {% ifequal nav "val" %}class="active"{% endifequal %}>
                                        <a href="javascript:void(0)" aria-expanded="true"><i style="color: #8d97ad" class="fa fa-align-left"></i> <span>Valutazione</span></a>
                                        <ul class="collapse">
                                            <li {% ifequal subnav "val-cert" %}class="active"{% endifequal %}>
                                                <a href="{% url 'valutazione:cert' %}">
                                                    <i style="color: #8d97ad" class="ti-sharethis"></i>&nbsp;&nbsp;&nbsp;Corsi / Cert
                                                </a>
                                            </li>
                                            <li {% ifequal subnav "val-level" %}class="active"{% endifequal %}>
                                                <a href="{% url 'valutazione:level' %}">
                                                    <i style="color: #8d97ad" class="ti-bookmark-alt"></i>&nbsp;&nbsp;&nbsp;Level
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if user.is_superuser %}
                                <li {% ifequal nav "doc" %}class="active"{% endifequal %}>
                                    <a href="javascript:void(0)" aria-expanded="true"><i style="color: #8d97ad" class="fa fa-align-left"></i> <span>Amministrazione</span></a>
                                    <ul class="collapse">
                                        <li {% ifequal subnav "doc-rep" %}class="active"{% endifequal %}>
                                            <a href="/admin/" target="_blank">
                                                <i style="color: #8d97ad" class="ti-receipt"></i>&nbsp;&nbsp;&nbsp;Database
                                            </a>
                                        </li>
                                        <li {% ifequal subnav "doc-rep" %}class="active"{% endifequal %}>
                                            <a href="{% url 'valutazione:upload' %}" target="_blank">
                                                <i style="color: #8d97ad" class="ti-receipt"></i>&nbsp;&nbsp;&nbsp;upload
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
            </div>
        </div>

core/templates/core/permission_denied.html
<html>
{% load static %}
    <head>
        <title>RESTRICTED AREA</title>
        <style>
            * { margin: 0; padding: 0; }

            html {
                background: url({% static 'no_access.png'%}) no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
            }

        </style>
    </head>
    <body>
        <
    </body>
</html>

core/templates/core/user_form.html
{% extends 'core/index.html' %}

{% load staticfiles %}

{% block head_title %}SOC H24{% endblock %}

{% block custom_page_level_css %}{% endblock %}

{% block body_main %}
    <div class="login-area" style="background-color: rgba(67,72,82,1);height: 800px">
            <div class="container">
                <div class="login-box ptb--100" >
                    <form style="margin-top: 0px;">
                        <div class="login-form-head">
                            <h4>Sign up</h4>
                            <p>Form per creare un nuovo Utente</p>
                        </div>
                        <div class="login-form-body">
                            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% include 'connessionianomale/form-template.html' %}
                                <div class="submit-btn-area">
                                    <button id="form_submit" type="submit">Submit <i class="ti-arrow-right"></i></button>
                                </div>
                            </form>
                        </div>
                    </form>
                </div>
            </div>
        </div>

{% endblock %}

{% block custom_page_level_javascript %}{% endblock %}